# Generated by Django 3.2.9 on 2022-04-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220430_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='mach',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
