# Generated by Django 3.2.9 on 2022-04-30 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_machine_mach'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Blog',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='blog',
        ),
    ]
