# Generated by Django 3.2.9 on 2022-05-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220501_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashString', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
        migrations.AddField(
            model_name='machine',
            name='cryptext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.cryptstring'),
        ),
    ]
