# Generated by Django 3.2.9 on 2022-05-19 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220518_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptstring',
            name='HashString',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
