# Generated by Django 3.2.6 on 2022-05-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_cryptstring_hashstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='expiry',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
