# Generated by Django 3.2.9 on 2022-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_machine_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
